# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.16.3 ]
  pull_request:
    branches: [ 1.16.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Rename the built jar
      run: mv build/libs/toastclient-1.0.0.jar toastclient-$GITHUB_RUN_NUMBER.jar
    - name: Send Discord build message
      env:
        WEBHOOK: ${{ secrets.BUILD_DISCORD_WEBHOOK }}
      run: "curl -X POST -H \"Content-Type: application/json\" -d '{\"content\": \"Build number $GITHUB_RUN_NUMBER from commit $GITHUB_SHA:\"}' \"$WEBHOOK\""
    - name: Upload client jar
      env:
        WEBHOOK: ${{ secrets.BUILD_DISCORD_WEBHOOK }}
      run: "curl -F 'data=@toastclient-$GITHUB_RUN_NUMBER.jar' $WEBHOOK"
