# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Download obfuscator
      run: wget https://github.com/superblaubeere27/obfuscator/releases/download/v1.9.3/obfuscator-1.9.3.jar -O obfuscator.jar
    - name: Create obfuscator config
      run: echo \{\"input\":\"/Users/willem/git/ToastClient/build/libs/toastclient-1.0.0.jar\",\"output\":\"/Users/willem/obf.jar\",\"script\":\"function isRemappingEnabledForClass\(node\) \{\\n    var flag1 \\u003d \!node.name.startsWith\(\\\"com/google/gson\\\"\)\;\\n    var flag2 \\u003d \!node.name.startsWith\(\\\"toast/client/lemongui/clickgui/settings\\\"\)\;\\n    return flag1 \\u0026\\u0026 flag2\;\\n\}\\nfunction isObfuscatorEnabledForClass\(node\) \{\\n    var flag1 \\u003d \!node.name.startsWith\(\\\"com/google/gson\\\"\)\;\\n    var flag2 \\u003d \!node.name.startsWith\(\\\"toast/client/lemongui/clickgui/settings\\\"\)\;\\n    return flag1 \\u0026\\u0026 flag2\;\\n\}\",\"libraries\":\[\],\"Crasher\":\{\"Enabled\":false\},\"InvokeDynamic\":\{\"Enabled\":false\},\"HWIDPRotection\":\{\"Enabled\":false,\"HWID\":\"FFCCABD426C0A88AEDF0AA4362FC4361\"\},\"Optimizer\":\{\"Enabled\":false,\"Replace String.equals\(\)\":false,\"Replace String.equalsIgnoreCase\(\)\":false,\"Optimize static string calls\":false\},\"LineNumberRemover\":\{\"Enabled\":true,\"Rename local variables\":true,\"Remove Line Numbers\":true,\"Remove Debug Names\":true,\"Add Local Variables\":true,\"New SourceFile Name\":\"\"\},\"StringEncryption\":\{\"Enabled\":true,\"HideStrings\":false,\"AES\":false\},\"NumberObfuscation\":\{\"Enabled\":true,\"Extract to Array\":true,\"Obfuscate Zero\":true,\"Shift\":false,\"And\":false,\"Multiple Instructions\":true\},\"ReferenceProxy\":\{\"Enabled\":false\},\"ShuffleMembers\":\{\"Enabled\":true\},\"InnerClassRemover\":\{\"Enabled\":true,\"Remap\":false,\"Remove Metadata\":true\},\"NameObfuscation\":\{\"Enabled\":false\},\"Packager\":\{\"Enabled\":false,\"Use MainClass from the JAR manifest\":true,\"Main class\":\"org.example.Main\"\},\"FlowObfuscator\":\{\"Enabled\":true,\"Mangle Comparisons\":true,\"Replace GOTO\":true,\"Replace If\":true,\"Bad POP\":true,\"Bad Concat\":true,\"Mangle Switches\":false,\"Mangle Return\":false,\"Mangle Local Variables\":false\},\"HideMembers\":\{\"Enabled\":true\},\"Inlining\":\{\"Enabled\":false\}\} > config
    - name: Obfuscate
      run: FILENAME=toastclient-$GITHUB_RUN_ID.jar && java -jar obfuscator.jar --jarIn ./build/libs/toastclient-1.0.0.jar --jarOut $FILENAME --config config
    - name: Send message to discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        UPDATESROLE: <@&711977862302924810>
        BOT_NAME: "Toast Client™ Releases"
      run: COMMITMESSAGE=`git log --format=%B -n 1` && UPDATEMSG=$UPDATESROLE\ New\ build\ [$GITHUB_RUN_ID]!\ Changelog:\ \`\`\`$COMMITMESSAGE\`\`\` && curl -H "Content-Type:application/json" -X POST -d "{\"username\":\"$BOTNAME\", \"content\":\"$UPDATEMSG\"}" $DISCORD_WEBHOOK
    - name: Upload to discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: curl -H 'Content-Type:multipart/form-data' -X POST -F "file=@$FILENAME" $DISCORD_WEBHOOK
    
